[[regexes]]
  name = "example regex entry"
  description = "example regex entry description"
  re = "(?P<msg>.*)"

[options]
  show_matches = true
  show_misses = false
  show_all_matches = false
  match_sample_size = 0
  show_multiple_matches = false

[plugin]
  id = 8876
  name = "suricata-dns-enhanced"
  version = "v1.0.0"
  description = ""
  log_file = "/var/log/suricata-dns.log"
  website = "https://gitlab.sedara.io/av-plugins/suricata-dns-enhanced"
  log_format = "-"

[vendor]
  name = "Open Information Security Foundation"
  model = "Suricata DNS"
  version = "2.x"
  per_asset = false

[author]
  name = "Sedara, LLC."
  email = "devs@sedarasecurity.com"
