[[regexes]]
  name = "Suricata DNS Entry"
  description = ""
  re = '''level=\S+\smsg=(?P<udone>\S+)\sdestip=(?P<resolvdstip>\IPV4)\sdestport=(?P<resolvdstport>\PORT)\snettype=(?P<udfive>(?P<pluginsid>\d))\sqtype=(?P<udtwo>\S+)\squery=(?P<udthree>\S+)\sresponse=(\")?(?P<udfour>[^\"].+[^\"])(\")?(\sseen=(?P<udseven>\d+))?\ssourceip=(?P<resolvsrcip>\IPV4)\ssourceport=(?P<srcport>\PORT)\stxtype=(?P<udsix>\d)'''

[[regexes]]
  name = "Suricata DNS Response Entry"
  description = ""
  re = '''.*msg=dns-response-value\sdestination=(?P<dstip>\IPV4)\sid=(?P<udone>\S+)(\sseen=(?P<udtwo>\d+))?\ssourceip=(?P<srcip>\IPV4)'''

[options]
  show_matches = true
  show_misses = false
  show_all_matches = false
  match_sample_size = 0
  show_multiple_matches = false

[plugin]
  id = 88876
  name = "suricata-dns-enhanced"
  version = "v1.0.7"
  description = ""
  log_file = "/var/log/suricata-dns-daemon.out.log"
  website = "https://gitlab.sedara.io/av-plugins/suricata-dns-enhanced"
  log_format = "-"

[vendor]
  name = "Open Information Security Foundation"
  model = "Suricata DNS"
  version = "2.x"
  per_asset = false

[author]
  name = "Sedara, LLC."
  email = "devs@sedarasecurity.com"
